### ISSUE TITLE
Storage of JOSM Presets 

### ISSUE THREAD

**Issue by timwaters** [hotosm/sds-server#13]
Each project should have the ability to upload a JOSM preset and any of the users on that project download it. 

Upload, storage.
Show current preset, admin upload new one, users to download preset

**Comment by emirhartato** [comment]
Is it also possible that when we upload JOSM presets it will automatically creates a new project? I think it's important so people won't have to write the code for presets and on new project page.

**Comment by timwaters** [comment]
Yes.

Uploading of presets will occur on the new project page, yes.  
Replacing of presets will occur on the edit project page.

**Comment by timwaters** [comment]
working on this one now

**Comment by timwaters** [comment]
![image](https://f.cloud.github.com/assets/48941/60224/da12ad60-5c01-11e2-97e6-c8c778527ed5.png)

![image](https://f.cloud.github.com/assets/48941/60226/fa4325ec-5c01-11e2-804d-1172975e9bd2.png)

**Comment by timwaters** [comment]
439d4b82891019715f73fe3c4b38f3b909bbb1cd

Admin can upload a JOSM preset when creating a project. The admin can upload a new preset when editing. Links to the preset is shown when viewing the preset. 

For normal users, a link to download the preset is shown on the right hand side bar when viewing a record

**Comment by timwaters** [comment]
presets are stored in RAILS_ROOT/public/presets/{project_id/filename.xml 
for example for project with an id of 2

RAILS_ROOT/public/presets/2/IndoJosmPreset.xml

the URL for this would be

"http://sdsserver.com/presets/2/IndoJosmPreset.xml" 

marking as closed.

**Comment by emirhartato** [comment]
cool! will test this soon! :)

On Fri, Jan 11, 2013 at 10:21 PM, Tim Waters notifications@github.comwrote:

> presets are stored in RAILS_ROOT/public/presets/{project_id/filename.xml
> for example for project with an id of 2
> 
> RAILS_ROOT/public/presets/2/IndoJosmPreset.xml
> 
> the URL for this would be
> 
> "http://sdsserver.com/presets/2/IndoJosmPreset.xml"
> 
> marking as closed.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hotosm/sds-server/issues/13#issuecomment-12148451.

## 

_Best Regards,
Emir Hartato_
_Humanitarian OpenStreetMap Team *
*
Using OpenStreetMap
*_
for Humanitarian Response
*_& Economic Development_
_Ph: +6287766721375 | *_Skype: emir.hartato*
_t: @emirhartato_
_http://whateverisaid.wordpress.com_

**Comment by timwaters** [comment]
Here's one I made earlier: http://sds.geothings.net:3000/presets/1/Presets_building.xml-preset.xml

(Lemme know if  http://sds.geothings.net:3000 goes down, it tends to do that occasionally. )
