### ISSUE TITLE
Easy access to Map Search

### ISSUE THREAD

**Issue by emirhartato** [hotosm/sds-server#19]
http://ec2-46-51-156-173.eu-west-1.compute.amazonaws.com/

One other thing is, I think there should be easy access to Map Search. I mean, after user is on object properties page, the map on the right corner should be clickable and user will be bring into slippy map on Map Search page without going back to Home page.

**Comment by timwaters** [comment]
Nice idea, would need permalink for map search page

**Comment by timwaters** [comment]
Done. Mapsearch now map has a permalink added to it, bottom right.

On the small detail map on the object properties page ,it has a link to open that in the mapsearch page.

http://ec2-46-51-156-173.eu-west-1.compute.amazonaws.com/mapsearch?lat=51.52367&lon=-0.13655&zoom=17&layers=BF
