### ISSUE TITLE
Load OSM Geometries Error

### ISSUE THREAD

**Issue by emirhartato** [hotosm/sds-server#22]
http://ec2-46-51-156-173.eu-west-1.compute.amazonaws.com/
In Map Search, when I zoomed to the area I want and click "Load OSM Geometries", nothing happen.

**Comment by timwaters** [comment]
This server uses data from the OpenStreetMap Dev Database.

The server only has some data at the moment. There should be data here: 

http://api06.dev.openstreetmap.org/?lat=51.52472&lon=-0.12936&zoom=17&layers=M

I suspect that you were looking at an area where there was no actual data.
