### ISSUE TITLE
Switch to live/production server

### ISSUE THREAD

**Issue by emirhartato** [hotosm/sds-server#24]
Hello,
We are going to test the SDS for TOT training next week, somewhere between 18-22 March. So far the new SDS works really good.

To make sure things work, I think it's time to switch OpenStreetMap Dev Database to live/production server.

Thanks.

**Comment by timwaters** [comment]
Will do.

Please note:

1) this testing server was meant to show the development progress of the software, and is **not meant for production use** but will work okay with the main live OSM API.  

2) Data will be deleted from it in the future. 

3) It is running on very low spec machine (ec2 free tier micro instance)  it may not be able to cope efficiently with multiple connections at once.

I think once everything is good, it would be deployed to a HOT maintained server.

**Comment by emirhartato** [comment]
How many users do you think it can hold up at the same time? Can it hold up
around 20?

**Comment by timwaters** [comment]
The server has 2 unicorn worker processes (the default is 10) - but it should be able to handle many connections with the 2 workers. Basically if a worker is busy, it cannot process a new request - so things could be slow.

**Comment by timwaters** [comment]
Okay the testing server has been switched to use the live OSM API
