### ISSUE TITLE
Easier way to convert XML presets to JOSN for projects

### ISSUE THREAD

**Issue by emirhartato** [hotosm/sds-server#25]
Is there any easier way to convert XML presets automatically to JOSN? Sorry for the hassle because I just wondering the best way to teach the SDS admin who new to JOSN to create a new project.

Thanks

**Comment by timwaters** [comment]
At the moment there is some difference between an XML JOSM preset file which an admin can upload and any user in that project can download for use in JOSM, and the tags definition field for a project which is in JSON format. Essentially, the tags definition replaces the partials - so from one easy field for each project into a laborious process to define a new project. 

This format will be documented. 

---

I think there is some overlap between the tags definition and the presets, but they do benefit from being different. 

For example, you have 2 projects, Hospitals, Doctors. Both projects have their own tags definition of 5 tags each, and their presets. Two of the tags are the same and shared "organisation name".

You want to add a new project "Healthcare" which contains the tags for hospitals and doctors - you add these 8 tags to this tags definition.  You don't need to merge in the JOSM presets, as users can continue to use the existing ones. But you may want to map some new ones, like "number of clinics". 

So, Healthcare project has 9 tags it is interested in, (8 from Doctors and Hospitals and 1 new) but the JOSM presets for this it could only have the extra one. 

Or it need not have a preset at all - if all the editing is done on the website. 

Any changes to a project does not need users to re download a JOSM preset.

**Comment by timwaters** [comment]
From the updated documentation:
Currently the definition for the tags that are in a project are stored in the database in a field called “tags_definition” this is stored as text but needs to be  valid JSON. The definition is a solution to the hard coded forms and data in the previous version of this applications “partials”.  
It is recommended that the JSON be valid, and a utility such as http://jsonlint.com can be used to help with this. In the future, the specification of these tags could be simplified, through a form builder perhaps, or some JSON validation could be added. 
The following gives an example of a definition in JSON format.
A tag must have a “type”, “tag” and “en”
“type” can be one of “text”, “date”, “select”, “url”
“en” is the English translation for name of the tag
Translations for the name of the tag are added by giving the locale as a key, For example
“id” is the Indonesian translation for the tag
The following is an example of a tags definition for a project:

```
[ 
{       "type": "text",
        "tag": "hot:simple:name",
        "en": "Name"
   },
    {
        "type": "text",
        "tag": "hot:simple:mobile",
        "id": "Nomor Handphone",
        "en": "Mobile"
    },
    {
        "type": "date",
        "tag": "hot:simple:date",
        "id": "Tanggal",
        "en": "Date"
    },
    {
        "type": "select",
        "tag": "hot:simple:choice",
        "en": "Choice",
        "options": [
            "yes",
            "no",
            "maybe",
            "of course"
        ]
    }
]
```

The definition is an Array ([..])of objects (contained in the curly brackets{..}) . Each tag object has the following: tag, type, en. “tag” defines the specified tag that is wanted. For example "tag": "hot:simple:mobile"  - “type“ defines the type of tag for the purposes of display and editing. For example a tag where "type": "date" is given will show a date selection widget in the form on the application, and a type of select will show a drop down selection box, composed of the entries in the “options“ box. “en” is the english name for the tag and “id” is the Indonesian name. You can add extra translations in this way.
